USE sucos;

SELECT LTRIM("      OLÁ") AS RESULTADO;
SELECT RTRIM("OLÁ       ") AS RESULTADO;
SELECT TRIM("   OLÁ   ") AS RESULTADO;
SELECT CONCAT('OLÁ'," ", "TUDO BEM","?") AS RESULTADO;
SELECT UPPER("Olá, tudo bem?") AS RESULTADO;
SELECT LOWER(CONCAT('OLÁ'," ", "TUDO BEM","?")) AS RESULTADO;
SELECT SUBSTRING("OLÁ TUDO BEM?",6,4) AS RESULTADO;

SELECT CONCAT(NOME, " (",CPF,")") AS RESULTADO FROM tabela_de_clientes;

SELECT NOME,CONCAT(ENDERECO_1," ",ENDERECO_2,", ", BAIRRO,", ",CIDADE, ", ",ESTADO) FROM tabela_de_clientes;

SELECT CURDATE();
SELECT CURRENT_DATE();
SELECT CURRENT_TIMESTAMP();
SELECT YEAR(CURRENT_TIMESTAMP());
SELECT DAY(CURRENT_TIMESTAMP());
SELECT MONTH(CURRENT_TIMESTAMP());
SELECT MONTHNAME(CURRENT_TIMESTAMP());
SELECT DATEDIFF(CURRENT_TIMESTAMP(),'2019-01-01') AS RESULTADO;
SELECT DATEDIFF(CURRENT_TIMESTAMP(),'1994-12-11') AS RESULTADO;
SELECT DATEDIFF(CURRENT_TIMESTAMP(),'2000-11-25') AS RESULTADO;
SELECT CURRENT_TIMESTAMP() AS DIA_HOJE, DATE_SUB(CURRENT_TIMESTAMP(),INTERVAL 5 DAY) AS RESULTADO;
SELECT DISTINCT DATA_VENDA, DAYNAME(DATA_VENDA) AS DIA, 
MONTHNAME(DATA_VENDA) AS MÊS, YEAR(DATA_VENDA) FROM notas_fiscais;
SELECT NOME, DATEDIFF(CURRENT_TIMESTAMP(),DATA_DE_NASCIMENTO) AS IDADE_ATUAL FROM tabela_de_clientes;

SELECT(23+((25-2)/2)*45) AS RESULTADO;
SELECT CEILING(12.333333232323) AS RESULTADO;
SELECT ROUND(12.33333232323) AS RESULTADO;
SELECT FLOOR(12.7777232323) AS RESULTADO;
SELECT ROUND(12.7777232323) AS RESULTADO;
SELECT RAND() AS RESULTADO;
SELECT NUMERO, QUANTIDADE, PRECO FROM itens_notas_fiscais;
SELECT NUMERO, QUANTIDADE, PRECO, QUANTIDADE*PRECO AS FATURAENTO
FROM itens_notas_fiscais;
SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE*PRECO, 2) AS FATURAENTO
FROM itens_notas_fiscais;
SELECT ROUND(SUM(N.IMPOSTO*(I.QUANTIDADE*I.PRECO)),2) AS IMPOSTO_2016 FROM notas_fiscais N 
INNER JOIN itens_notas_fiscais I
ON I.NUMERO=N.NUMERO
WHERE YEAR(N.DATA_VENDA)=2016;

SELECT CURRENT_TIMESTAMP() AS RESULTADO;
SELECT CONCAT('O dia de hoje é : ', CURRENT_TIMESTAMP()) AS RESULTADO;
SELECT CONCAT('O dia de hoje é : ', DATE_FORMAT(CURRENT_TIMESTAMP(),'%W ,%d/%m/%y - %U')) AS RESULTADO;
SELECT SUBSTRING(CONVERT(23.3,CHAR),1,1) AS RESULTADO;
SELECT CONCAT("O cliente ", C.NOME, " Faturou ", ROUND(SUM(N.FATURAMENTO),2), " no ano de ",N.ANO_VENDA)
FROM tabela_de_clientes C INNER JOIN (SELECT N.CPF AS CPF,SUM(I.QUANTIDADE*I.PRECO) AS FATURAMENTO, 
YEAR(N.DATA_VENDA) AS ANO_VENDA 
FROM notas_fiscais N INNER JOIN itens_notas_fiscais I ON N.NUMERO=I.NUMERO
GROUP BY CPF,ANO_VENDA) 
N ON C.CPF=N.CPF
GROUP BY C.NOME,N.ANO_VENDA;




