USE sucos;

/*QUANTIDADE VENDIDA POR SABOR EM 2016*/
SELECT VENDA_SABOR.SABOR, VENDA_SABOR.ANO,VENDA_SABOR.QUANTIDADE,
ROUND((VENDA_SABOR.QUANTIDADE/VENDA_TOTAL.QUANTIDADE)*100,2) AS PARTICIPACAO
FROM (SELECT TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO=INF.NUMERO
INNER JOIN tabela_de_produtos TP
ON TP.CODIGO_DO_PRODUTO=INF.CODIGO_DO_PRODUTO
WHERE YEAR(NF.DATA_VENDA)=2016
GROUP BY TP.SABOR, YEAR(NF.DATA_VENDA)
ORDER BY QUANTIDADE DESC) VENDA_SABOR
INNER JOIN
(SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO=INF.NUMERO
INNER JOIN tabela_de_produtos TP
ON TP.CODIGO_DO_PRODUTO=INF.CODIGO_DO_PRODUTO
WHERE YEAR(NF.DATA_VENDA)=2016
GROUP BY YEAR(NF.DATA_VENDA)) VENDA_TOTAL
ON VENDA_TOTAL.ANO=VENDA_SABOR.ANO
ORDER BY VENDA_SABOR.QUANTIDADE DESC
;