START TRANSACTION;

SELECT * FROM VENDEDORES;
UPDATE VENDEDORES SET COMISSAO=COMISSAO*1.15;
SELECT * FROM VENDEDORES;

ROLLBACK;

SELECT * FROM VENDEDORES;

START TRANSACTION;

SELECT * FROM VENDEDORES;
UPDATE VENDEDORES SET COMISSAO=COMISSAO*1.15;
SELECT * FROM VENDEDORES;

COMMIT;

SELECT * FROM VENDEDORES;

START TRANSACTION;

INSERT INTO vendedores Value
('99999', 'Joao Da Silva','Icaraí', 0.08,'2012-01-15',0);
UPDATE VENDEDORES SET COMISSAO=COMISSAO*1.15;
SELECT * FROM vendedores;
ROLLBACK;

START TRANSACTION;
DELETE FROM vendedores;
ROLLBACK;