USE SUCOS;
SELECT * FROM notas_fiscais;
SELECT * FROM itens_notas_fiscais;

SELECT NF.CPF, NF.DATA_VENDA, INF.QUANTIDADE 
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO=INF.NUMERO;

SELECT NF.CPF, DATE_FORMAT(NF.DATA_VENDA, "%Y-%m") AS MES_ANO, SUM(INF.QUANTIDADE) 
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO=INF.NUMERO
GROUP BY NF.CPF, MES_ANO;

SELECT * FROM tabela_de_clientes TC;

SELECT TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA AS QUANTIDADE_LIMITE
FROM tabela_de_clientes TC;

SELECT X.CPF, X.NOME, X.MES_ANO, X.QUANTIDADE_VENDAS,X.QUANTIDADE_LIMITE,
CASE WHEN X.QUANTIDADE_LIMITE-X.QUANTIDADE_VENDAS<0 THEN "INVÁLIDO"
ELSE "VÁLIDO" END AS STATUS_VENDA
FROM(
SELECT NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, "%Y-%m") AS MES_ANO, 
SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS, MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO=INF.NUMERO
INNER JOIN tabela_de_clientes TC
ON TC.CPF=NF.CPF
GROUP BY NF.CPF, MES_ANO, TC.NOME) X

;
SELECT X.CPF, X.NOME, X.MES_ANO, X.QUANTIDADE_VENDAS,X.QUANTIDADE_LIMITE,
CASE WHEN X.QUANTIDADE_LIMITE-X.QUANTIDADE_VENDAS<0 THEN "INVÁLIDO"
ELSE "VÁLIDO" END AS STATUS_VENDA,
(1 - (X.QUANTIDADE_LIMITE/X.QUANTIDADE_VENDAS)) * 100 AS QUANTO_PASSOU
FROM(
SELECT NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, "%Y-%m") AS MES_ANO, 
SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS, MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO=INF.NUMERO
INNER JOIN tabela_de_clientes TC
ON TC.CPF=NF.CPF
GROUP BY NF.CPF, MES_ANO, TC.NOME) X
WHERE (X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) < 0;

