USE sucos;

-- 3.35
EXPLAIN FORMAT=JSON SELECT A.NOME_DO_PRODUTO FROM tabela_de_produtos A;

-- 40933.10
EXPLAIN FORMAT=JSON SELECT A.NOME_DO_PRODUTO, C.QUANTIDADE
FROM tabela_de_produtos A
INNER JOIN itens_notas_fiscais C ON A.codigo_do_produto = C.codigo_do_produto;

-- 158078.93
EXPLAIN FORMAT=JSON SELECT A.NOME_DO_PRODUTO, YEAR(B.DATA_VENDA) AS ANO, C.QUANTIDADE
FROM tabela_de_produtos A
INNER JOIN itens_notas_fiscais C ON A.codigo_do_produto = C.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais B ON C.numero=B.numero;

-- 158078.93
EXPLAIN FORMAT=JSON SELECT A.NOME_DO_PRODUTO, YEAR(B.DATA_VENDA) AS ANO, SUM(C.QUANTIDADE) AS QUANTIDADE
FROM tabela_de_produtos A
INNER JOIN itens_notas_fiscais C ON A.codigo_do_produto = C.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais B ON C.numero=B.numero
GROUP BY A.NOME_DO_PRODUTO, YEAR(B.DATA_VENDA)
ORDER BY A.NOME_DO_PRODUTO, YEAR(B.DATA_VENDA);

-- 8724.06
EXPLAIN FORMAT=JSON SELECT * FROM notas_fiscais where DATA_VENDA="20170101";

ALTER TABLE notas_fiscais ADD INDEX (DATA_VENDA);

-- 46.81
EXPLAIN FORMAT=JSON SELECT * FROM notas_fiscais where DATA_VENDA="20170101";

ALTER TABLE NOTAS_FISCAIS DROP INDEX DATA_VENDA;

-- 8806.52
SELECT * FROM notas_fiscais where DATA_VENDA="20170101";
