DROP PROCEDURE IF EXISTS Soma_Dias_Notas;
DELIMITER $$
CREATE PROCEDURE `Soma_Dias_Notas`(vDataInicial date, vDataFinal date)
BEGIN
	DECLARE vContador INT;
	DECLARE NUMNOTAS INTEGER;
	DECLARE TEMPNOTAS INTEGER;
	SET vContador=0;
    SET NUMNOTAS=0;
	WHILE TIMESTAMPDIFF(DAY, ADDDATE(vDataInicial, INTERVAL vContador DAY),vDataFinal)>0
	DO
		SELECT COUNT(*) INTO TEMPNOTAS FROM NOTAS_FISCAIS WHERE DATA_VENDA=ADDDATE(vDataInicial, INTERVAL vContador DAY);
        SET NUMNOTAS=NUMNOTAS+TEMPNOTAS;
        SELECT CONVERT(ADDDATE(vDataInicial, INTERVAL vContador DAY),CHAR(15)),TEMPNOTAS;
        SET vContador=vContador+1;
	END WHILE;
	SELECT CONVERT(ADDDATE(vDataInicial, INTERVAL vContador DAY),CHAR(15)),NUMNOTAS;
END $$
DELIMITER $$

CALL Soma_Dias_Notas("2017-01-01","2017-01-10");