USE SUCOS;
DROP TABLE IF EXISTS TABELA_ALEATORIOS;
CREATE TABLE TABELA_ALEATORIOS(NUMERO INT);
DROP PROCEDURE IF EXISTS Tabela_Numeros;
DELIMITER $$
CREATE PROCEDURE `Tabela_Numeros` ()
BEGIN
	DECLARE CONTADOR INT DEFAULT 0;
	DECLARE ALEATORIO INT;
	WHILE CONTADOR<100
	DO
		SELECT FLOOR((RAND()*(1001))) INTO ALEATORIO;
		INSERT INTO TABELA_ALEATORIOS VALUES (ALEATORIO);
        SET CONTADOR=CONTADOR+1;
	END WHILE;
END $$
DELIMITER $$

CALL TABELA_NUMEROS;

SELECT * FROM TABELA_ALEATORIOS;