SELECT VENDAS.ID_VENDEDOR, VENDEDORES.NOME_VENDEDOR, SUM(VENDAS.QTD_VENDIDA) FROM VENDAS, VENDEDORES WHERE VENDAS.ID_VENDEDOR=VENDEDORES.ID_VENDEDOR GROUP BY VENDAS.ID_VENDEDOR;
SELECT A.ID_VENDEDOR, E.NOME_VENDEDOR, SUM(A.QTD_VENDIDA) FROM VENDAS AS A, VENDEDORES AS E WHERE A.ID_VENDEDOR=E.ID_VENDEDOR GROUP BY A.ID_VENDEDOR;
SELECT A.ID_VENDEDOR, E.NOME_VENDEDOR, SUM(A.QTD_VENDIDA) FROM VENDAS A, VENDEDORES E WHERE A.ID_VENDEDOR=E.ID_VENDEDOR GROUP BY A.ID_VENDEDOR;
SELECT A.ID_VENDEDOR, E.NOME_VENDEDOR, SUM(A.QTD_VENDIDA) FROM VENDAS A INNER JOIN VENDEDORES E ON A.ID_VENDEDOR=E.ID_VENDEDOR GROUP BY A.ID_VENDEDOR;
SELECT L.NOME_LIVRO, V.QTD_VENDIDA FROM LIVROS L LEFT JOIN VENDAS V ON L.ID_LIVRO = V.ID_LIVRO WHERE V.QTD_VENDIDA IS NULL;
SELECT V.ID_LIVRO,L.NOME_LIVRO, V.QTD_VENDIDA FROM LIVROS L RIGHT JOIN VENDAS V ON L.ID_LIVRO = V.ID_LIVRO;