SELECT * FROM LIVROS;
SELECT ID_LIVRO AS "Código do Livro" FROM LIVROS;
SELECT * FROM LIVROS WHERE CATEGORIA ="Biografia";
SELECT * FROM LIVROS WHERE CATEGORIA = "ROMANCE" AND PREÇO<48;
SELECT * FROM LIVROS WHERE CATEGORIA = "POESIA" AND NOT (AUTORIA="Luís Vaz de Camões" OR AUTORIA="Gabriel Pedrosa");
SELECT DISTINCT ID_LIVRO FROM VENDAS WHERE ID_VENDEDOR=1 ORDER BY ID_LIVRO;

DELETE FROM LIVROS WHERE ID_LIVRO=8;

SET SQL_SAFE_UPDATES=0;
UPDATE LIVROS SET PREÇO=0.9*PREÇO;
SET SQL_SAFE_UPDATES=1;