USE vendas_sucos;
CREATE TABLE TAB_IDENTITY(ID INT AUTO_INCREMENT, DESCRITOR VARCHAR(20), PRIMARY KEY(ID));

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE1');

SELECT * FROM TAB_IDENTITY;
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE1'),('CLIENTE2');
DELETE FROM TAB_IDENTITY WHERE ID=4;
INSERT INTO TAB_IDENTITY VALUES (NULL, 'CLIENTE4');
INSERT INTO TAB_IDENTITY VALUES (100,'CLIENTE5');
INSERT INTO TAB_IDENTITY VALUES (NULL,'CLIENTE6');
SELECT * FROM TAB_IDENTITY;