USE vendas_sucos;
SELECT * FROM produtos;

UPDATE produtos SET PRECO_LISTA=5 WHERE CODIGO = '1000889';
SELECT * FROM produtos;

UPDATE produtos SET EMBALAGEM = 'PET', TAMANHO = '1 LITRO', DESCRITOR = 'Sabor da Montanha - 1 Litro - Uva' WHERE CODIGO='1000889';
SELECT * FROM produtos;

SELECT * FROM produtos WHERE SABOR = 'Maracujá';

UPDATE produtos SET PRECO_LISTA = PRECO_LISTA*1.10 WHERE SABOR = 'Maracujá';

SELECT * FROM clientes WHERE CPF="19290992743";
UPDATE clientes SET ENDERECO = 'R. Jorge Emílio 23', BAIRRO='Santo Amaro', CIDADE='São Paulo', ESTADO='SP', CEP='8833223' WHERE CPF="19290992743";
SELECT * FROM clientes WHERE CPF="19290992743";

SELECT * FROM VENDEDORES;

SELECT * FROM sucos.TABELA_DE_VENDEDORES;

SELECT * FROM VENDEDORES A
INNER JOIN sucos.TABELA_DE_VENDEDORES B
ON A.MATRICULA = SUBSTRING(B.MATRICULA,3,3);

UPDATE VENDEDORES A
INNER JOIN sucos.TABELA_DE_VENDEDORES B
ON A.MATRICULA = SUBSTRING(B.MATRICULA,3,3)
SET A.FERIAS=B.DE_FERIAS;

UPDATE VENDEDORES A
INNER JOIN clientes B
ON A.BAIRRO = B.BAIRRO
SET B.VOLUME_COMPRA=B.VOLUME_COMPRA*1.3;